### PR TITLE
Update favorite-foods.txt

### PR DESCRIPTION
**Pull request by thielj46**

### CODE REVIEW

**Comment by likwam29** [comment]
you should squash this.

**Comment by likwam29** [comment]
nvm ill do it

**Comment by likwam29** [comment]
are you getting emails for this?

**Comment by likwam29** [comment]
jessica!!!!

**Comment by thielj46** [comment]
stop fooling around

**Comment by thielj46** [comment]
matt

**Comment by thielj46** [comment]
maaaaaaaaaaaaaat

**Comment by thielj46** [comment]
matt matt matt

**Pull request merged**
